# .github/workflows/submit.yml (in student template repo)
name: Evaluate Hash Function

on:
  push:
    paths:
      - 'MyString.java'
  workflow_dispatch:

permissions:
  contents: write

env:
  LEADERBOARD_URL: https://your-org.github.io/hash-contest-leaderboard/

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download evaluation code
        run: |
          curl -sfL "https://raw.githubusercontent.com/your-org/hash-contest-leaderboard/main/src/AbstractController.java" -o AbstractController.java
          curl -sfL "https://raw.githubusercontent.com/your-org/hash-contest-leaderboard/main/src/GitHubController.java" -o GitHubController.java
          curl -sfL "https://raw.githubusercontent.com/your-org/hash-contest-leaderboard/main/src/HashSet.java" -o HashSet.java
          curl -sfL "https://raw.githubusercontent.com/your-org/hash-contest-leaderboard/main/corpus.txt" -o corpus.txt

      - name: Compile
        id: compile
        run: |
          mkdir -p out
          if ! javac -d out *.java 2>err.txt; then
            echo "error<<EOF" >> $GITHUB_OUTPUT
            cat err.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Run evaluation
        id: eval
        if: steps.compile.outcome == 'success'
        run: |
          cp corpus.txt out/
          cd out

          if ! OUTPUT=$(timeout 30s java GitHubController 2>&1); then
            echo "error<<EOF" >> $GITHUB_OUTPUT
            echo "$OUTPUT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          fi

          PSEUDO=$(echo "$OUTPUT" | grep "^PSEUDONYM:" | cut -d' ' -f2)
          COLLISIONS=$(echo "$OUTPUT" | grep "^COLLISIONS:" | cut -d' ' -f2)

          echo "pseudonym=$PSEUDO" >> $GITHUB_OUTPUT
          echo "collisions=$COLLISIONS" >> $GITHUB_OUTPUT

      - name: Save result
        if: steps.eval.outputs.collisions
        run: |
          echo '{"pseudonym": "${{ steps.eval.outputs.pseudonym }}", "collisions": ${{ steps.eval.outputs.collisions }}, "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > result.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add result.json
          git diff --staged --quiet || git commit -m "Update result: ${{ steps.eval.outputs.collisions }} collisions"
          git push

      - name: Trigger leaderboard update
        if: steps.eval.outputs.collisions
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.LEADERBOARD_TOKEN }}" \
            https://api.github.com/repos/your-org/hash-contest-leaderboard/dispatches \
            -d '{"event_type": "update"}'

      - name: Summary
        if: always()
        run: |
          if [ -n "${{ steps.compile.outputs.error }}" ]; then
            echo "## ❌ Compilation Failed" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.compile.outputs.error }}" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          elif [ -n "${{ steps.eval.outputs.error }}" ]; then
            echo "## ❌ Evaluation Failed" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.eval.outputs.error }}" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "## ✅ Results" >> $GITHUB_STEP_SUMMARY
            echo "**Pseudonym:** ${{ steps.eval.outputs.pseudonym }}" >> $GITHUB_STEP_SUMMARY
            echo "**Collisions:** ${{ steps.eval.outputs.collisions }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "[View Leaderboard](${{ env.LEADERBOARD_URL }})" >> $GITHUB_STEP_SUMMARY
          fi
